apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-deploy
  labels:
    app: devops-cicd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-cicd-app
  template:
    metadata:
      labels:
        app: devops-cicd-app
    spec:
      containers:
      - name: devops-cicd-container
        image: ppraveen/devops-cicd-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-cicd-np-service
  labels:
    app: devops-cicd-app
spec:
  selector:
    app: devops-cicd-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
